// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace biz.avantco.Entities
{
    public partial class Newsletter
    {
        public int Id { get; set; }
        public string Email { get; set; }
    }
}