// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace biz.avantco.Entities
{
    public partial class ScheduleAppointment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Age { get; set; }
        public string Company { get; set; }
        public string PhoneCode { get; set; }
        public string PhoneNumber { get; set; }
        public DateTime? Date { get; set; }
        public string TimeDay { get; set; }
    }
}